import("lanes/utils.rb")

default_platform(:ios)

lane :testflight_deploy do
  skip_docs
  setup_ci
  update_code_signing_settings(use_automatic_signing: false)

  app_store_connect_api_key

  update_build_number
  match
  gym
  pilot

  add_version_git_tag
end
