# RULE LIST

disabled_rules:
  - private_over_fileprivate
  - force_cast
  - line_length
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - nesting
  - no_fallthrough_only
  - opening_brace
  - statement_position
  - switch_case_alignment
  - todo
  - function_parameter_count

opt_in_rules:
  - indentation_width



#FILES

included:
  - "../../Scoofin"
  - "../../Packages"

excluded:
  - "../../Packages/ILPackages/il-localization/Sources/ILLocalization/Localization.g.swift"



# RULES CONFIGURATION

colon:
  flexible_right_spacing: true

identifier_name:
  min_length: 1
  max_length: 100
  excluded: ["_$id"]
  allowed_symbols: ["_"]

type_name:
  min_length: 2
  max_length: 100

large_tuple:
  warning: 5
  error: 6

function_body_length:
  warning: 50

trailing_whitespace:
  ignores_empty_lines: true



# OPT IN RULES CONFIGURATION

indentation_width:
  indentation_width: 1