name: TestFlight deploy
 
on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
 
jobs:
 deploy:
   runs-on: macos-13
   
   steps:
     - uses: actions/checkout@v2
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: "15.0.1"
 
     - name: Prepare SSH key
       uses: webfactory/ssh-agent@v0.8.0
       with:
         ssh-private-key: ${{ secrets.SCO_GIT_CERT_SSH_KEY }}

     - name: Set up Ruby environment
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: 3.2.1
         bundler-cache: true

     - name: Update Swift version
       uses: swift-actions/setup-swift@v1
       with:
         swift-version: "5.9.0"

     - name: Swift infrastructure info
       run: |
         swift --version
         xcode-select --print-path

     - name: Build & upload iOS binary
       run: bundle exec fastlane --verbose testflight_deploy
       env:
         APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.SCO_ASC_AUTH_KEY_ID }}
         APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.SCO_ASC_AUTH_ISSUER_ID }}
         APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.SCO_ASC_AUTH_KEY }}
         APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: true
         MATCH_PASSWORD: ${{ secrets.SCO_MATCH_PASSWORD }}
       continue-on-error: true

     - name: Upload app-store .ipa and .dsyms artifacts
       uses: actions/upload-artifact@v2
       with:
         name: app-store ipa & dsyms
         path: |
           ${{ github.workspace }}/scoofin-iOS.ipa
           ${{ github.workspace }}/*.app.dSYM.zip